### ISSUE TITLE
uname reports 5.6.0

### ISSUE THREAD

**Issue by RlndVt** [abelian424/archiso-bcachefs-mainline#1]
After installing (and booting into) the linux-mainline-bcachefs packages which should provide 5.6.10, uname reports 5.6.0 instead.

**Comment by abelian424** [comment]
The package will report the latest Linux version from this file:
https://github.com/koverstreet/bcachefs/blob/master/Makefile Right now that
is 5.6.0, which may or may not actually have further point updates.

**Comment by RlndVt** [comment]
Is it not possible to maintain a patch to match the point updates?

**Comment by abelian424** [comment]
I don't intend to fork the bcachefs repo as I don't really have the setup
to efficiently download and recompile for each point update. What you could
do is git clone in the makepkg cache directory before making package, and
then edit the PKGBUILD so that it doesn't replace the git repo. Then you
could build with any point update. I'm sure koverstreet does his own
testing with kernel builds, so it should be updated for 5.7 if not sooner.

**Comment by abelian424** [comment]
Actually, I could try making a patch, but it would be hackish. If you could
provide one, that would be great.

**Comment by abelian424** [comment]
I contacted koverstreet and asked him if there would be any problem with
building a higher point update. All in all, it would be simplest if he just
updated the repo to change the makefile to a higher point update. If
there's no issue, he should do it. I'll let you know.

**Comment by abelian424** [comment]
Fixed PKGBUILD to build with whichever number is given in the _pkgverpntrel variable. all it does is change the build file to say the correct point version.
